### PR TITLE
Fixing some things and slight improvements in NotifyClose()

### PR DESCRIPTION
**Pull request by brettneese**
This pull request: 

- Fixed an issue with exit animations not properly displaying when mixed
(say FadeIn and SlideOut). https://github.com/mouse0270/bootstrap-notify/issues/115

- Adds a function (`notifyCloseExcept()`) that allows closing all notifications
except for certain types of notifications (so, you can persist Warnings but
not Infos).

- Expands `NotifyClose()` to support passing in notification types in order to remove only those types of notifications (for example, removing all Warnings) and added the ability to include arbitrary jquery selectors to target removing notifications in more ways.

### CODE REVIEW

**Comment by mouse0270** [comment]
Why do you check if selector is equal to warning and if so set it to danger?

**Comment by brettneese** [comment]
We use "warning" as our highest level error, which actually creates a `alert-danger`. Wanted to make it easier for us to remember.

Feel free to yank that out of there, I forgot I included it in this pull request haha.

**Comment by mouse0270** [comment]
Okay, yeah it would need to be removed, that appears to specific to your application sorry. I'll merge and update this pull request this weekend.

**Comment by brettneese** [comment]
yeah, that's chill.

i should be taking care of that before it hits bootstrap-notify anyway. :+1:

**Pull request merged**
