### PR TITLE
Version 3.1.3

### PR DESCRIPTION
**Pull request by mouse0270**

### CODE REVIEW

**Comment by zimme** [comment]
:+1:

I'll deprecate my wrapper package in favour of your new and shiny package this weekend :stuck_out_tongue_closed_eyes:

**Comment by mouse0270** [comment]
Thank you. Wouldn't have been able to do it without you!

**Comment by zimme** [comment]
No problem, glad to help. We need to get dem nice libraries for Meteor too :shipit:

**Comment by mouse0270** [comment]
Well, I am happy to support as much as I can. I just need help with the learning curve of setting everything up. Meteor is going to be easy because of the http://autopublish.meteor.com/. Which is great because it takes one less thing off my mind when updating.

**Pull request merged**
