### PR TITLE
Addedd updateMult method

### PR DESCRIPTION
**Pull request by GeoffreyFrogeye**
Allow update multiple elements using an array of commands.

Not sure if the name fits.
I thought about making `update` test if the first argument is an array, but IMO it's not a good idea.

### CODE REVIEW

**Comment by mouse0270** [comment]
Included in the 3.0.1 release. Just a little different then yours.

**Comment by GeoffreyFrogeye** [comment]
Thanks !
Just FYI, this breaks API compatibility

**Comment by mouse0270** [comment]
Oops. I have a patch for this, will upload today.

**Comment by mouse0270** [comment]
A patch has been released so it will support both single call update methods and the new multi call update methods

**Comment by mouse0270** [comment]
A patch has been released so it will support both single call update methods and the new multi call update methods

**Comment by GeoffreyFrogeye** [comment]
LGTM

**Pull request closed without merging**
