### PR TITLE
Meteor integration

### PR DESCRIPTION
**Pull request by zimme**
So I've finally had time to update the Meteor integration.

With this PR you just need to setup [Autopublish](http://autopublish.meteor.com) and when you tag a new release it will take care of publishing to [Atmosphere](http://atmospherejs.com) for you.

1. Go to  [Autopublish](http://autopublish.meteor.com).
2. Login with github.
3. Navigate to the list of your repositories.
4. Activate autopublish for `bootstrap-notify`

That's all you need to do on Autopublish.

Then you will need to add `meteorpublish` to your package maintainers with the command:
```sh
meteor admin maintainers mouse0270:bootstrap-notify --add meteorpublish
```

And this should be it!

Just remember to update the `package.js` file when you bump versions as you already do with `package.json`, `bower.json` and `composer.json`.

I also took the liberty to fix your grunt setup a bit. Adding dependencies as devDependencies instead as it's only needed for development.

I added meteor testing to the grunt setup and I also mapped `npm test` to `grunt test`.

Feel free to ping me if you ever setup Travis-CI and I'll help you with the meteor setup. But with the current setup the only Meteor specific thing you need to add to `.travis.yml` is:

```yaml
sudo: required
language: node_js
node_js:
  - 0.12

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  ```

### CODE REVIEW

**Comment by mouse0270** [comment]
I'll set this up later today....

I don't know if you know this or not, but I actually tried to do this a little bit ago. haha.

**Comment by zimme** [comment]
Currently the `grunt test` will fail because of jshint part is failing.

To manually run Meteor tests use one of the following:
To get test results in browser
```sh
meteor test-packages ./
```
To get the test results on commandline
```sh
node_modules/.bin/spacejam test-packages ./
```

**Comment by zimme** [comment]
Yeah I actually saw that but I had time set aside for my meteor packages tonight so it worked out nicely :stuck_out_tongue_closed_eyes:
Trying to hand over responsibility to library maintainers for Meteor integration for all my "wrapper" packages. One which was bootstrap-growl. I'll unpublish my wrapper package once I see this package working.

**Comment by mouse0270** [comment]
Well wasn't that convenient. Did you notice my failure on [Autopublish](http://autopublish.meteor.com) where it was not only double posting, but not even succeeding.

Thank you for putting all of the work into getting this ready. I'll do my best to remember to change the versions. I noticed that when I uploaded version 3.0.0 that I never updated any of those other files. I am trying to watch it a little more.

**Comment by zimme** [comment]
If I where you I would add another grunt task for bumping versions in all affected files. That way you can just run `grunt bump-version` and you're done. :smile:

**Comment by zimme** [comment]
Yeah I saw that too. It most likely failed because of `meteorpublish` not being added to your package maintainers.

**Comment by zimme** [comment]
So you might need to do a manual publish first with this command.
```sh
meteor publish --create
```

And after that remove the `.versions` file and then go on to setting up Autopublish and once setup Autopublish should take care of the next release.

**Comment by splendido** [comment]
...if you're looking for a grunt task to update version numbers, lets have a look [here](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Caveat#replacing-the-version-in-packagejsbowerjson-etc) :)

**Pull request merged**
